[package]
name = "raydium-amm-v3"
version = "0.1.0"
description = "Anchor client and source for Raydium concentrated liquidity AMM"
edition = "2021"
keywords = ["solana", "anchor", "raydium"]

[lib]
crate-type = ["cdylib", "lib"]
name = "raydium_amm_v3"
doctest = false

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []
client = []
no-log-ix-name = []
init_if_needed = []
enable-log = []
devnet = []
paramset = []

[dependencies]
anchor-lang = { git = "https://github.com/coral-xyz/anchor", rev = "0453672", features = [
    "init-if-needed",
] }
anchor-spl = { git = "https://github.com/coral-xyz/anchor", rev = "0453672", features = [
    "metadata",
] }
solana-program = "2.1"
spl-memo = "6.0.0"
uint = { git = "https://github.com/raydium-io/parity-common", package = "uint" }
mpl-token-metadata = { version = "5.1.0" }
spl-token-metadata-interface = { version = "0.6.0" }
bytemuck = { version = "1.19.0", features = ["derive", "min_const_generics"] }
arrayref = { version = "0.3.6" }
solana-security-txt = "1.1.1"

[dev-dependencies]
quickcheck = "0.9"
proptest = "1.0"
rand = "0.8.5"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = true
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
